resources:
#  - kafka.yaml
#  - minio-claim0-persistentvolumeclaim.yaml
#  - minio-deployment.yaml
#  - minio-service.yaml
#  - env-configmap.yaml
#  - video-loader-deployment.yaml
#  - splitter-deployment.yaml
#  - transcoder-deployment.yaml
#  - concater-deployment.yaml
