apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert --out manifests
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: minio
  name: minio
spec:
  nodeSelector:
    beta.kubernetes.io/arch: amd64
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: minio
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert --out manifests
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: minio
    spec:
      containers:
      - args:
        - minio
        - server
        - /data
        env:
        - name: MINIO_ADDRESS
          value: :9000
        - name: MINIO_CONSOLE_ADDRESS
          value: :9001
        - name: MINIO_ROOT_PASSWORD
          value: minio_password
        - name: MINIO_ROOT_USER
          value: minio_user
        image: quay.io/minio/minio:latest
        imagePullPolicy: ""
        name: minio
        ports:
        - containerPort: 9000
        - containerPort: 9001
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: minio-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: minio-claim0
        persistentVolumeClaim:
          claimName: minio-claim0
status: {}
