apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: video-transcode
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 8
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824