name: ci

on:
  push:
    branches:
      - 'master'


jobs:
  docker:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: downcase REPO name as output
        id: downcase
        run: |
          echo "::set-output name=downcase::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')"
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ steps.downcase.outputs.downcase }}/transcoder:latest,ghcr.io/${{ steps.downcase.outputs.downcase }}/transcoder:${{ github.sha }}
      - name: Build and push gpu
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          file: ./cuda.dockerfile
          push: true
          tags: ghcr.io/${{ steps.downcase.outputs.downcase }}/transcoder-gpu:latest,ghcr.io/${{ steps.downcase.outputs.downcase }}/transcoder-gpu:${{ github.sha }}